# Generated by Django 3.1.4 on 2020-12-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('epic', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aadhar', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('isNominee', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('epic', 'aadhar')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='ai_evm.voter')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='ai_evm.voter')),
            ],
        ),
    ]
