# Generated by Django 3.1.4 on 2020-12-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_evm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(default='dummy@mailinator.com', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_evm.voter')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='ai_evm.party'),
        ),
    ]
